Use babel-loader to enable code-splitting of bundles
jenkinsci/pipeline-graph-view-plugin pull request #223
Opened 2023-02-23 14:50 UTC by timbrown5

Added babel-loader and switch to it for jsx? and TSX? files.

Bundles before:
![Screenshot 2023-02-23 at 14 41 14](https://user-images.githubusercontent.com/4447764/220941267-9e638d33-8280-4fb3-81f9-2e575bad1bb3.png)

Bundles after:
![Screenshot 2023-02-23 at 14 43 33](https://user-images.githubusercontent.com/4447764/220941296-52b2f685-25c5-4743-b4a5-d86d6e2778e2.png)

Command:
`./node_modules/.bin/webpack --profile --json > stats.json ; ./node_modules/.bin/webpack-bundle-analyzer ./stats.json`

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did

2023-02-23 15:07 UTC, timja requested changes

2023-02-23 15:07 UTC, timja commented on package.json
> +    "bable-loader": "^0.0.1-security",
typo squatted package? https://www.npmjs.com/package/bable-loader

2023-02-23 15:08 UTC, timja commented
What are the numbered ones at the start?

Pipeline console view looks a lot smaller

2023-02-23 15:29 UTC, timbrown5 commented
Before:
![Screenshot 2023-02-23 at 15 27 27](https://user-images.githubusercontent.com/4447764/220952987-1a9d3c36-4e47-4606-808b-4fe98d216f4b.png)

After:
![Screenshot 2023-02-23 at 15 29 24](https://user-images.githubusercontent.com/4447764/220953191-089979f0-4959-4df3-ad6f-eec185ebe8b3.png)

2023-02-23 15:33 UTC, timbrown5 commented
Not sure why iconList.json takes up so much space in console view?

2023-02-23 21:08 UTC, timbrown5 commented
Here is a before and after video of the lazy loading (with network throttling enabled):
Before:
https://user-images.githubusercontent.com/4447764/221029987-1f8cfd03-73d4-4908-9c4f-a99b22cebcf1.mov

After:
https://user-images.githubusercontent.com/4447764/221030009-9bcc951a-6f1b-4514-8830-92e4103a7871.mov

2023-02-24 09:19 UTC, timja commented
Wow nice, anything remaining on this?

2023-02-24 14:00 UTC, timbrown5 commented
I'm happy it solves the large bundle problem, but not sure if there's a
better/preferred way to do it?
Also not sure if it breaks anything (I did a cursory look at the console
and graph gives and they render as expected).

On Fri, 24 Feb 2023, 09:19 Tim Jacomb, ***@***.***> wrote:

> Wow nice, anything remaining on this?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/223#issuecomment-1443292375>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABB54FAVORBPC37SM65QV3LWZB4JXANCNFSM6AAAAAAVFXPVWA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-02-24 14:15 UTC, timja commented
I haven't found any issues, couldn't really notice any difference.

When I had slow 3g throttle on I was getting faster on the original and 1mb bundle instead of 600 or so kb on the network tab.

but happy to try this out anyway.

2023-03-09 22:23 UTC, timja approved these changes

2023-03-09 22:30 UTC, timbrown5 commented
I've found some additional savings - mostly removing ionicons (which was causing the large iconList.json file). Size is down from 2.MB to 1.28MB.

<img width="2205" alt="Screenshot 2023-03-09 at 22 24 55" src="https://user-images.githubusercontent.com/4447764/224174740-c689ccf4-d47b-47d4-9d49-bd049ed4ba9a.png">

I believe I fixed the scaling issues with the SvgStatus class (which allowed me to remove icoicons). It also adds the correct colors to the DataTreeView:
Before:
<img width="651" alt="Screenshot 2023-03-09 at 22 28 39" src="https://user-images.githubusercontent.com/4447764/224174909-1b008707-4bc2-47ea-bb8e-1e539fb69449.png">

After: 
<img width="647" alt="Screenshot 2023-03-09 at 22 27 57" src="https://user-images.githubusercontent.com/4447764/224174923-845e14af-a6a2-4a53-9515-3e6b430995bb.png">

2023-03-09 22:34 UTC, timja commented
nice!

2023-03-09 22:45 UTC, timja commented on src/main/frontend/pipeline-console-view/pipeline-console/main/PipelineConsoleModel.tsx
> +//export { default as StepStatus } from "../../../step-status/StepStatus";
```suggestion
```

2023-03-10 10:40 UTC, merged